config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'users/new'

  get 'users/create'
  
  get 'users/index' => 'users#index'
  
  get 'users/show' => 'users#show'
  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  
  patch 'user' => 'users#update'

  root 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
   enum jobtype: {"노출":0, "비노출":1}
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase } 
    validates :name, presence: true, length: { maximum: 50 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    PERMITS = %w(email password password_confirmation name type ) 
    
    has_secure_password
    has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  # protect_from_forgery with: :null_session
  # protect_from_forgery except: [:create]
  protect_from_forgery unless: -> { request.format.json? }
  include SessionsHelper

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:username, :userphone, :start, :startpoint, :goal, :jobtype)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def new
  end
  
  def create
    user = User.find_by(:email => params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      # current_user.to_json(:only => [:id])
      render :json => {:id => current_user.id}
      # redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def index
  end
  
  def new
  end
  
  def show
    users = User.all.each
    userarr = users.collect{ |a| a }
    render :json => { :users => userarr }
  end
  
  def create
    user = User.new(user_params)
    if user.email == User.where(:email)
      redirect_to :root
    else
      user.save
    end
    
    redirect_to :root
  end
  
  def update
    user = User.find(params[:id])
    user.longitude = params[:longitude]
    user.lat = params[:lat]
    user.save
  end
  
  private
  
  def user_params
      params.permit(User::PERMITS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 전달된 사용자로 로그인 
    def log_in(user) 
        session[:user_id] = user.id 
    end 
    # 현재 로그인 한 사용자를 반환(로그인 한 경우에만) 
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) 
    end 
    # 로그인 되어있다면 true 를 그렇지 않다면 false 를 반환 
    def user_signed_in? 
        !current_user.nil? 
    end
    
    def log_out 
      session.destroy
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= current_user.to_json(:only => [:id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href='/users/new'>회원가입</a>
<%= link_to '로그아웃', logout_path, method: :delete %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :userphone %><br>
    <%= f.text_field :userphone %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :startpoint %><br>
    <%= f.text_field :startpoint %>
  </div>
  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="field">
    <%= f.label :jobtype %><br>
    <%= f.text_field :jobtype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Userphone</th>
      <th>Start</th>
      <th>Startpoint</th>
      <th>Goal</th>
      <th>Jobtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.username %></td>
        <td><%= post.userphone %></td>
        <td><%= post.start %></td>
        <td><%= post.startpoint %></td>
        <td><%= post.goal %></td>
        <td><%= post.jobtype %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Userphone:</strong>
  <%= @post.userphone %>
</p>

<p>
  <strong>Start:</strong>
  <%= @post.start %>
</p>

<p>
  <strong>Startpoint:</strong>
  <%= @post.startpoint %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @post.goal %>
</p>

<p>
  <strong>Jobtype:</strong>
  <%= @post.jobtype %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_tag '/users' do %>
    이메일
    <input type="email" name="email"><br>
    패스워드
    <input type="password" name="password"><br>
    패스워드 확인
    <input type="password" name="password_confirmation"><br>
    이름
    <input type="string" name="name"><br>
    <input type="hidden" name="type" value=""><br>
    <%= csrf_meta_tag %> 
    <input type="submit" value="회원가입">
<% end %>

app/views/users/show.html.erb
<%= @users.to_json(:only => [:id]) %>